// Copyright (c) 2021 Terminus, Inc.
//
// This program is free software: you can use, redistribute, and/or modify
// it under the terms of the GNU Affero General Public License, version 3
// or later ("AGPL"), as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

export default {
  success: true,
  data: [
    {
      clusterName: 'terminus-dev',
      clusterType: 'kubernetes',
      key: 'EnvironmentalOverview',
      cnName: '环境总览',
      enName: 'MicroService',
      href: '',
      params: {},
      children: [
        {
          clusterName: '',
          clusterType: '',
          key: 'Overview',
          cnName: '全局拓扑',
          enName: 'Overview',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: true,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'ServiceList',
          cnName: '服务列表',
          enName: 'ServiceList',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: true,
          onlyK8S: false,
          onlyNotK8S: false,
        },
      ],
      exists: true,
      mustExists: true,
      onlyK8S: false,
      onlyNotK8S: false,
    },
    {
      clusterName: 'terminus-dev',
      clusterType: 'kubernetes',
      key: 'ServiceObservation',
      cnName: '服务观测',
      enName: 'ServiceObservation',
      href: '',
      params: {},
      children: [
        {
          clusterName: '',
          clusterType: '',
          key: '',
          cnName: '',
          enName: '',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'ServiceAnalysis',
          cnName: '服务分析',
          enName: 'ServiceAnalysis',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'ErrorInsight',
          cnName: '错误分析',
          enName: 'ErrorInsight',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'Transaction',
          cnName: '链路追踪',
          enName: 'Transaction',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
      ],
      exists: true,
      mustExists: true,
      onlyK8S: false,
      onlyNotK8S: false,
    },
    {
      clusterName: 'terminus-dev',
      clusterType: 'kubernetes',
      key: 'QueryAnalysis',
      cnName: '查询分析',
      enName: 'QueryAnalysis',
      href: '',
      params: {},
      children: [
        {
          clusterName: '',
          clusterType: '',
          key: 'Dashboard',
          cnName: '仪表盘',
          enName: 'Dashboard',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'QuickQuery',
          cnName: '快速查询',
          enName: 'QuickQuery',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
      ],
      exists: true,
      mustExists: false,
      onlyK8S: false,
      onlyNotK8S: false,
    },
    {
      clusterName: 'terminus-dev',
      clusterType: 'kubernetes',
      key: 'AlarmManagement',
      cnName: '告警管理',
      enName: 'AlarmManagement',
      href: '',
      params: {},
      children: [
        {
          clusterName: '',
          clusterType: '',
          key: 'AlertStrategy',
          cnName: '告警策略',
          enName: 'AlertStrategy',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'AlarmHistory',
          cnName: '告警历史',
          enName: 'AlarmHistory',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'RuleManagement',
          cnName: '规则管理',
          enName: 'RuleManagement',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'NotifyGroupManagement',
          cnName: '通知组管理',
          enName: 'NotifyGroupManagement',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: false,
        },
      ],
      exists: true,
      mustExists: true,
      onlyK8S: false,
      onlyNotK8S: false,
    },
    {
      clusterName: 'terminus-dev',
      clusterType: 'kubernetes',
      key: 'EnvironmentSet',
      cnName: '环境设置',
      enName: 'EnvironmentSet',
      href: '',
      params: {},
      children: [
        {
          clusterName: '',
          clusterType: '',
          key: 'AccessConfig',
          cnName: '接入配置',
          enName: 'AccessConfig',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: false,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: true,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'MemberManagement',
          cnName: '成员管理',
          enName: 'MemberManagement',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: false,
          mustExists: false,
          onlyK8S: false,
          onlyNotK8S: true,
        },
        {
          clusterName: '',
          clusterType: '',
          key: 'ComponentInfo',
          cnName: '组件信息',
          enName: 'ComponentInfo',
          href: '',
          params: {
            key: 'Overview',
            tenantGroup: '48ffa5fe11d4107840cc0a6dc75723ac',
            tenantId: 'g1e951cdabbef4ba48b11f3b4b9cf9df7',
            terminusKey: '48ffa5fe11d4107840cc0a6dc75723ac',
          },
          children: [],
          exists: true,
          mustExists: false,
          onlyK8S: true,
          onlyNotK8S: false,
        },
      ],
      exists: true,
      mustExists: true,
      onlyK8S: false,
      onlyNotK8S: false,
    },
  ],
};
